version: '3.1'
services:
  stats-client:
    build: stats/stats_client/
    container_name: ewm-stats-client
    ports:
      - "9090:9090"
    depends_on:
      [ stats-server ]
    environment:
      - STAT_CLIENT_PORT=9090
      - STAT_SERVER_ADDRESS=http://stats-server:9091

  stats-server:
    build: stats/stats_server/
    container_name: ewm-stats-server
    ports:
      - "9091:9091"
    depends_on:
      [ stats-db ]
    environment:
      - STAT_SERVER_PORT=9091
      - DB_NAME=statistics
      - DB_HOST=stats_db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    hostname: stats_db
